version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3001:3001"
  front:
    build: ./front
    depends_on:
      - app
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: fedorbilichenko
      POSTGRES_DB: disks_sales
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"